import os
from .base_extractor import BaseEntityModule
import logging

logger = logging.getLogger("EntityExtraction")

class DocumentationGenerator(BaseEntityModule):
    """Module 10: Entity Documentation"""
    
    def run(self, entities: dict):
        doc_path = os.path.join(self.cfg.paths.docs_dir, "entity_documentation.md")
        
        with open(doc_path, "w") as f:
            f.write("# Enterprise Entity Documentation\n\n")
            f.write("Generated by Phase 4 Entity Extraction Pipeline.\n\n")
            
            for k, df in entities.items():
                if df.is_empty():
                    continue
                f.write(f"## {k.capitalize()}\n")
                f.write(f"- **Total Extracted:** {df.height}\n")
                f.write(f"- **Attributes Available:** {', '.join(df.columns)}\n")
                f.write(f"- **Future Graph Usage:** Node type `{k.capitalize()}` for heterogeneous mapping.\n\n")
                
        logger.info("Entity Documentation Generated.")
